preset: laravel

disabled:
  - single_class_element_per_statement

finder:
  exclude:
    - "tests"
    - "node_modules"
    - "storage"
    - "vendor"
  not-name:
    - "AcceptanceTester.php"
    - "FunctionalTester.php"
    - "UnitTester.php"